name: Selenium Tests

on:
  push:
    branches: [ "develop" ] 
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Maven
      uses: comchangs/action-maven@master
      with:
        maven-version: '3.9.1'

    - name: Build and run tests
      run: |
        mvn clean install -Dmaven.test.failure.ignore=true

    - name: Upload test results (optional)
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports
